### ISSUE TITLE
Vagrant box and file links not working

### ISSUE THREAD

**Issue by karlwnw** [gocd/developer.go.cd#3]
Hello,

The Vagrant box and file linked in the documentation are not available (404) https://github.com/gocd/developer.go.cd/blob/master/2/2.1.md, https://developer.go.cd/current/2/2.1.html. Is there an up to date version somewhere?

Thanks!

**Comment by arvindsv** [comment]
Hey @karlwnw. It was not easy to keep it in sync with the codebase and it has been removed as an option (Essentially, it ended up being a huge vagrant box and was not very useful). I've removed the section from the documentation since it was confusing to multiple people (and you).

Hopefully, the other way is not very hard (or can be done in a VM).

**Comment by arvindsv** [comment]
It'll show up at https://developer.go.cd/16.4.0/2/2.1.html before 16.4 is released and will move to https://developer.go.cd/current/2/2.1.html once it is release.

**Comment by karlwnw** [comment]
Thanks! Indeed it was not so much about the vagrant box itself as how to get going.

**Comment by arvindsv** [comment]
If you're looking to contribute and having trouble, you can always head over to the gitter channel (https://gitter.im/gocd/gocd). There was a discussion [earlier today](https://gitter.im/gocd/gocd?at=571886293307b26736e35448) on that channel about making it easier for people to contribute. We definitely need to do that.
